## 1、numpy生成随机数组  

### 1.1numpy.random.random()　生成随机浮点数
默认为生成一个随机的浮点数，范围是在0.0~1.0之间，也可以通过参数size设置返回数据的size;

In [2]:
import numpy as np
n = np.random.random(2)
n

array([0.56080562, 0.62562617])

In [2]:
np.random.random(size=(2,3))

array([[0.41826139, 0.64622335, 0.35125422],
       [0.15014399, 0.13929184, 0.47550172]])

### 1.2 numpy.random.randint()　产生随机整数  
randint(low, high=None, size=None)  

numpy.random.randint()默认随机生一个整数int类型，可以指定这个整数的范围  

可指定范围和维度

In [5]:
# 生成小于8的随机整数
np.random.randint(8)

0

In [6]:
np.random.randint(6, size=3)

array([4, 1, 3])

In [11]:
np.random.randint(6, size=(3,2))

array([[4, 0],
       [1, 1],
       [4, 4]])

In [7]:
a = np.random.randint(6, size=(3,2))

In [8]:
a.ndim

2

In [10]:
a.shape
a.dtype

dtype('int32')

### 1.3 np.random.normal() 　高斯分布随机数
API: normal(loc=0.0, scale=1.0, size=None)  

loc：均值，scale：标准差，size：抽取样本的size  

In [12]:
np.random.normal(loc=0, scale=1, size=(2, 3))

array([[11.10779751, 11.61113509, 10.46239196],
       [ 8.54789605, 11.33319391, 10.11178401]])

### 1.4 numpy.random.randn()　标准正态分布随机数  

numpy.random.randn(d0, d1, …, dn)函数：   

从标准正态分布中返回一个(d0*d1* …* dn)维样本值

In [15]:
np.random.randn(4, 2)
np.random.randn(4, 2, 3)

array([[[-0.52392901,  0.88794599, -0.22325008],
        [ 2.00648201, -0.24455585, -0.37367723]],

       [[ 0.07675676, -0.02716576,  1.01050177],
        [ 0.05257999,  0.63186693,  0.11533548]],

       [[ 0.68003454, -0.4801352 , -0.15623364],
        [-1.70271516, -0.37976364, -2.3424709 ]],

       [[-0.87863599, -1.15911535, -2.8581279 ],
        [ 0.12883532, -0.90595313, -0.12131835]]])

### 1.5 numpy.random.rand()　生成[0, 1)间随机数  

numpy.random.rand(d0, d1, …, dn)函数：  

生成一个(d0*d1* …* dn)维位于[0, 1)中随机样本

In [16]:
np.random.rand(2,3)

array([[0.79905155, 0.82397741, 0.6451544 ],
       [0.58847049, 0.02363604, 0.52993123]])

### 1.6 numpy.random.shuffle()　随机打乱序列  

numpy.random.shuffle() 将序列的所有元素随机排序   

<传入参数可以是一个序列或者元组>

In [18]:
x = list(range(0,8,2))
print(x)
np.random.shuffle(x)
x

[0, 2, 4, 6]


[4, 6, 2, 0]

### 1.7 numpy.random.choice()　随机选取序列的一个元素  
numpy.random.choice()可以从序列(字符串、列表、元组等)中随机选取，返回一个列表，元组或字符串的随机项。

In [19]:
np.random.choice(['a','b','c','d','e'])

'a'

In [20]:
np.random.choice(5, 8) # 返回8个小于5的元素

array([4, 4, 2, 2, 1, 3, 1, 2])

## 2、ndarray的序列创建

In [21]:
data1 = [6, 7.5, 8, 0, 1]

In [22]:
arr1 = np.array(data1)  # 一维数组创建

In [23]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [24]:
data2 = [[1, 2, 3, 4],
         [5, 6, 7, 8]]

In [25]:
arr2 = np.array(data2)  # 二维数组创建

In [26]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [47]:
np.asarray(data1)

array([6. , 7.5, 8. , 0. , 1. ])

In [48]:
arr2.ndim 

2

In [49]:
arr2.shape

(2, 4)

In [28]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.ones_like(arr1)

array([1., 1., 1., 1., 1.])

In [31]:
np.zeros(10), np.zeros((3,5))

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]))

In [32]:
np.zeros_like(arr2)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [33]:
np.empty((2,3,5))

array([[[1.44545539e-311, 9.58487353e-322, 0.00000000e+000,
         0.00000000e+000, 0.00000000e+000],
        [5.02034658e+175, 9.36757509e-067, 7.08087345e-057,
         1.03339721e-071, 4.17382766e+025],
        [1.47763641e+248, 1.16096346e-028, 7.69165785e+218,
         1.35617292e+248, 6.69015430e+020]],

       [[3.04544881e-047, 5.89978983e-062, 8.37167229e-062,
         4.25765019e-096, 6.32299154e+233],
        [6.48224638e+170, 5.22411352e+257, 5.74020278e+180,
         8.37174974e-144, 1.41529402e+161],
        [9.16651763e-072, 4.09857243e+097, 7.13183515e-067,
         4.09338820e+126, 4.06321267e-317]]])

注：np.empty不是返回全为0的数组，它返回的是一些未初始化的垃圾值

In [16]:
np.arange(5)  # python中range的数组版

array([0, 1, 2, 3, 4])

In [34]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.eye(5, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [19]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 2、numpy数据类型

In [21]:
# astype方法显式转换ndarray的dtype
arr = np.array([1, 2, 3, 4])
arr.dtype

dtype('int32')

In [23]:
float_arr = arr.astype(np.float32)
float_arr 

array([1., 2., 3., 4.], dtype=float32)

In [35]:
arr = np.array([1.1, -2.2, 3.3])

In [36]:
int_arr = arr.astype(np.int32)
int_arr

array([ 1, -2,  3])

In [37]:
data = [1,2,3]

In [38]:
np.array(data,dtype=np.float32)

array([1., 2., 3.], dtype=float32)