### 元素级的运算

In [2]:
import numpy as np

In [3]:
arr = np.array([[1, 2, 3,],
                [4, 5, 6]])

In [5]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [4]:
arr + arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

### 广播 将标量广播到各个元素

In [9]:
arr * 5

array([[ 5, 10, 15],
       [20, 25, 30]])

In [4]:
arr + 5

array([[ 6,  7,  8],
       [ 9, 10, 11]])