In [1]:
import numpy as np

In [2]:
arr = np.arange(5)

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [6]:
# 计算各个元素的平方
np.exp2(arr)

array([ 1.,  2.,  4.,  8., 16.])

sqrt 和 exp 是一元函数，另外一些（如add，maximum）接受两个数组
（也叫二元函数）

In [7]:
x = np.random.randn(8)
y = np.random.randn(8)

In [8]:
x

array([ 0.05742201,  1.20091186,  1.29978579, -0.27726285, -0.63800407,
        0.37929116,  0.82612004, -1.00093931])

In [9]:
y

array([ 1.21083735, -0.48793572,  0.81167457, -0.2171338 , -0.7397729 ,
       -0.30925121,  0.93174265,  0.00234523])

In [10]:
np.maximum(x,y)

array([ 1.21083735,  1.20091186,  1.29978579, -0.2171338 , -0.63800407,
        0.37929116,  0.93174265,  0.00234523])

In [11]:
# 有些ufunc可以返回多个数组，如modf
arr = np.random.randn(5) * 5

In [12]:
arr

array([ 1.16908572,  6.67300052,  3.58331609,  1.61175057, -8.34731386])

In [16]:
np.modf(arr)  # 将数组的小数和整数部分以两个独立数组形式返回

(array([ 0.16908572,  0.67300052,  0.58331609,  0.61175057, -0.34731386]),
 array([ 1.,  6.,  3.,  1., -8.]))

In [17]:
# randn() 返回具有标准正态分布的序列。
arr = np.random.randn(2,3)
print(arr)

[[-1.33928791 -0.69680785  0.52521556]
 [-2.12097846 -0.26731085 -0.67214109]]


In [18]:
np.ceil(arr)

array([[-1., -0.,  1.],
       [-2., -0., -0.]])

In [19]:
np.floor(arr)

array([[-2., -1.,  0.],
       [-3., -1., -1.]])

In [20]:
np.rint(arr)

array([[-1., -1.,  1.],
       [-2., -0., -1.]])

In [21]:
np.isnan(arr)

array([[False, False, False],
       [False, False, False]])

In [22]:
np.multiply(arr, arr)  # 相当于 *

array([[1.7936921 , 0.48554118, 0.27585138],
       [4.49854963, 0.07145509, 0.45177364]])

In [23]:
np.divide(arr, arr)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.where(arr > 0, 1, -1)

array([[-1, -1,  1],
       [-1, -1, -1]])

In [28]:
arr[arr>0] = 1
arr[arr<0] = -1

In [29]:
arr

array([[-1., -1.,  1.],
       [-1., -1., -1.]])

In [ ]:
print(np.ceil(arr))
print(np.floor(arr))
print(np.rint(arr))
print(np.isnan(arr))
print(np.multiply(arr, arr))
print(np.divide(arr, arr))
print(np.where(arr > 0, 1, -1))