## 1、tofile()和fromfile()

In [1]:
import numpy as np

In [2]:
a = np.arange(0,12)
a.shape = 3,4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
a.tofile("a.bin")

In [5]:
b = np.fromfile("a.bin",dtype=np.float)

In [6]:
b # 读入的数据有误

array([2.12199579e-314, 6.36598737e-314, 1.06099790e-313, 1.48539705e-313,
       1.90979621e-313, 2.33419537e-313])

In [7]:
a.dtype # 查看a的dtype

dtype('int32')

In [8]:
b = np.fromfile("a.bin",dtype=np.int32)

In [9]:
b # 数据是一维的

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
b.shape = 3,4 # 按照a的shape设定b的shape

In [11]:
b # 读取正确

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## 2、save()和load()

In [12]:
np.save("a.npy",a)
c = np.load("a.npy")
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
a = np.array([[1,2,3],[4,5,6]])
b = np.arange(0,1,0.1)
c = np.sin(b)
c

array([0.        , 0.09983342, 0.19866933, 0.29552021, 0.38941834,
       0.47942554, 0.56464247, 0.64421769, 0.71735609, 0.78332691])

In [14]:
#如果想将多个数组保存到一个文件中，可以使用savez()
np.savez("result.npz",a,b,sin_array=c)

In [15]:
r = np.load("result.npz")

In [16]:
r["arr_0"] # 数组a

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
r["arr_1"] # 数组b

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [18]:
r["sin_array"] # 数组c

array([0.        , 0.09983342, 0.19866933, 0.29552021, 0.38941834,
       0.47942554, 0.56464247, 0.64421769, 0.71735609, 0.78332691])

## 3、savetxt()和loadtxt()

In [23]:
a = np.arange(0,12,0.5).reshape(4,-1)  # -1 表示让numpy自动判断第二个维度的大小

In [24]:
a

array([[ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ,  4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ,  7.5,  8. ,  8.5],
       [ 9. ,  9.5, 10. , 10.5, 11. , 11.5]])

In [25]:
np.savetxt("a.txt",a) # 缺省按照"%.18e"格式保存数值，以空格分割

In [26]:
np.loadtxt("a.txt")

array([[ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ,  4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ,  7.5,  8. ,  8.5],
       [ 9. ,  9.5, 10. , 10.5, 11. , 11.5]])

In [27]:
np.savetxt("a.txt",a,fmt="%d",delimiter=",") # 保存为整数，以逗号分割

In [28]:
np.loadtxt("a.txt",delimiter=",")

array([[ 0.,  0.,  1.,  1.,  2.,  2.],
       [ 3.,  3.,  4.,  4.,  5.,  5.],
       [ 6.,  6.,  7.,  7.,  8.,  8.],
       [ 9.,  9., 10., 10., 11., 11.]])

In [33]:
tmp = np.loadtxt("test.csv",dtype=np.str,delimiter=",")
tmp

array([['姓名', '年龄', '体重', '身高'],
       ['张三', '30', '75', '165'],
       ['李四', '45', '60', '170'],
       ['王五', '15', '30', '120']], dtype='<U3')

In [37]:
tmp[1:,1:]

array([['30', '75', '165'],
       ['45', '60', '170'],
       ['15', '30', '120']], dtype='<U3')

In [41]:
tmp[[1,2]]

array([['张三', '30', '75', '165'],
       ['李四', '45', '60', '170']], dtype='<U3')

In [42]:
data = tmp[1:,1:].astype(np.int32)

In [43]:
data

array([[ 30,  75, 165],
       [ 45,  60, 170],
       [ 15,  30, 120]])

## 4、文件对象file

In [44]:
a = np.arange(8)
b = np.add.accumulate(a)
c = a+b
f = open("result.npy","wb")

In [45]:
a,b,c

(array([0, 1, 2, 3, 4, 5, 6, 7]),
 array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32),
 array([ 0,  2,  5,  9, 14, 20, 27, 35]))

In [46]:
np.save(f,a)
np.save(f,b)
np.save(f,c)
f.close()

In [47]:
f = open("result.npy","rb")
np.load(f)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [48]:
np.load(f)

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [49]:
np.load(f)

array([ 0,  2,  5,  9, 14, 20, 27, 35])

In [50]:
np.load(f)

OSError: Failed to interpret file <_io.BufferedReader name='result.npy'> as a pickle

In [51]:
f.close()