In [1]:
import numpy as np

In [2]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

In [3]:
x

array([[1, 2],
       [3, 4]])

In [4]:
y

array([[5, 6],
       [7, 8]])

In [6]:
x.dot(y)

array([[19, 22],
       [43, 50]])

In [7]:
np.dot(x, y)

array([[19, 22],
       [43, 50]])

In [9]:
a=[1,5,7,9,4,3,1,7,3]
b=[4,46,456,748,54,2,4,4,16]
na=np.array(a).reshape((3,3))
nb=np.array(b).reshape((3,3))
result=np.dot(na,nb)

In [10]:
na

array([[1, 5, 7],
       [9, 4, 3],
       [1, 7, 3]])

In [11]:
nb

array([[  4,  46, 456],
       [748,  54,   2],
       [  4,   4,  16]])

In [12]:
result

array([[3772,  344,  578],
       [3040,  642, 4160],
       [5252,  436,  518]])

In [13]:
# 求逆
np.linalg.inv(na)

array([[-0.03169014,  0.11971831, -0.04577465],
       [-0.08450704, -0.01408451,  0.21126761],
       [ 0.20774648, -0.00704225, -0.1443662 ]])

In [14]:
na_inv = np.linalg.inv(na)
na_inv.dot(na)

array([[ 1.00000000e+00, -4.85722573e-17, -2.08166817e-17],
       [ 0.00000000e+00,  1.00000000e+00,  1.66533454e-16],
       [ 0.00000000e+00, -1.38777878e-16,  1.00000000e+00]])